'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ImpPfad() As String
            Get
                Return CType(Me("ImpPfad"),String)
            End Get
            Set
                Me("ImpPfad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ExpPfad() As String
            Get
                Return CType(Me("ExpPfad"),String)
            End Get
            Set
                Me("ExpPfad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PObjekteV() As Boolean
            Get
                Return CType(Me("PObjekteV"),Boolean)
            End Get
            Set
                Me("PObjekteV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property PObjekteX() As Integer
            Get
                Return CType(Me("PObjekteX"),Integer)
            End Get
            Set
                Me("PObjekteX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property PObjekteY() As Integer
            Get
                Return CType(Me("PObjekteY"),Integer)
            End Get
            Set
                Me("PObjekteY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("271")>  _
        Public Property PObjekteW() As Integer
            Get
                Return CType(Me("PObjekteW"),Integer)
            End Get
            Set
                Me("PObjekteW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("328")>  _
        Public Property PObjekteH() As Integer
            Get
                Return CType(Me("PObjekteH"),Integer)
            End Get
            Set
                Me("PObjekteH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PTextureV() As Boolean
            Get
                Return CType(Me("PTextureV"),Boolean)
            End Get
            Set
                Me("PTextureV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property PTextureX() As Integer
            Get
                Return CType(Me("PTextureX"),Integer)
            End Get
            Set
                Me("PTextureX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("338")>  _
        Public Property PTextureY() As Integer
            Get
                Return CType(Me("PTextureY"),Integer)
            End Get
            Set
                Me("PTextureY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("392")>  _
        Public Property PTextureW() As Integer
            Get
                Return CType(Me("PTextureW"),Integer)
            End Get
            Set
                Me("PTextureW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("337")>  _
        Public Property PTextureH() As Integer
            Get
                Return CType(Me("PTextureH"),Integer)
            End Get
            Set
                Me("PTextureH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WireframeV() As Boolean
            Get
                Return CType(Me("WireframeV"),Boolean)
            End Get
            Set
                Me("WireframeV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property GitterV() As Boolean
            Get
                Return CType(Me("GitterV"),Boolean)
            End Get
            Set
                Me("GitterV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property OrtoScale() As Integer
            Get
                Return CType(Me("OrtoScale"),Integer)
            End Get
            Set
                Me("OrtoScale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Letzte() As String
            Get
                Return CType(Me("Letzte"),String)
            End Get
            Set
                Me("Letzte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Programme\Steam\steamapps\common\OMSI 2")>  _
        Public Property OmsiPfad() As String
            Get
                Return CType(Me("OmsiPfad"),String)
            End Get
            Set
                Me("OmsiPfad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("410")>  _
        Public Property PEigenschaftenX() As Integer
            Get
                Return CType(Me("PEigenschaftenX"),Integer)
            End Get
            Set
                Me("PEigenschaftenX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property PEigenschaftenY() As Integer
            Get
                Return CType(Me("PEigenschaftenY"),Integer)
            End Get
            Set
                Me("PEigenschaftenY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PEigenschaftenV() As Boolean
            Get
                Return CType(Me("PEigenschaftenV"),Boolean)
            End Get
            Set
                Me("PEigenschaftenV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("630")>  _
        Public Property PEigenschaftenH() As Integer
            Get
                Return CType(Me("PEigenschaftenH"),Integer)
            End Get
            Set
                Me("PEigenschaftenH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property CamPaxColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("CamPaxColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("CamPaxColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property CamDriverColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("CamDriverColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("CamDriverColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property CamReflexColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("CamReflexColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("CamReflexColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\")>  _
        Public Property OpenPath() As String
            Get
                Return CType(Me("OpenPath"),String)
            End Get
            Set
                Me("OpenPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\")>  _
        Public Property ImportPath() As String
            Get
                Return CType(Me("ImportPath"),String)
            End Get
            Set
                Me("ImportPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property BackColor3D() As Global.System.Drawing.Color
            Get
                Return CType(Me("BackColor3D"),Global.System.Drawing.Color)
            End Get
            Set
                Me("BackColor3D") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property eMail() As String
            Get
                Return CType(Me("eMail"),String)
            End Get
            Set
                Me("eMail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property SaveInterval() As Integer
            Get
                Return CType(Me("SaveInterval"),Integer)
            End Get
            Set
                Me("SaveInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SaveIntervalActive() As Boolean
            Get
                Return CType(Me("SaveIntervalActive"),Boolean)
            End Get
            Set
                Me("SaveIntervalActive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SaveIntervalAuto() As Boolean
            Get
                Return CType(Me("SaveIntervalAuto"),Boolean)
            End Get
            Set
                Me("SaveIntervalAuto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pink")>  _
        Public Property PassColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("PassColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("PassColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property DriverColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("DriverColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DriverColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property AchsenColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("AchsenColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AchsenColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BackupAnlegen() As Boolean
            Get
                Return CType(Me("BackupAnlegen"),Boolean)
            End Get
            Set
                Me("BackupAnlegen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Programme\Steam\steamapps\common\OMSI 2\SDK\RepaintTool.exe")>  _
        Public Property RepToolPfad() As String
            Get
                Return CType(Me("RepToolPfad"),String)
            End Get
            Set
                Me("RepToolPfad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PfadeOrigBreite() As Boolean
            Get
                Return CType(Me("PfadeOrigBreite"),Boolean)
            End Get
            Set
                Me("PfadeOrigBreite") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LogDebug() As Boolean
            Get
                Return CType(Me("LogDebug"),Boolean)
            End Get
            Set
                Me("LogDebug") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoConvertO3D() As Boolean
            Get
                Return CType(Me("AutoConvertO3D"),Boolean)
            End Get
            Set
                Me("AutoConvertO3D") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property LineColor3D() As Global.System.Drawing.Color
            Get
                Return CType(Me("LineColor3D"),Global.System.Drawing.Color)
            End Get
            Set
                Me("LineColor3D") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property lastExportFormat() As Byte
            Get
                Return CType(Me("lastExportFormat"),Byte)
            End Get
            Set
                Me("lastExportFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property lastImportFormat() As Byte
            Get
                Return CType(Me("lastImportFormat"),Byte)
            End Get
            Set
                Me("lastImportFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CreatorID() As Integer
            Get
                Return CType(Me("CreatorID"),Integer)
            End Get
            Set
                Me("CreatorID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property o3dRemoveSpec() As Boolean
            Get
                Return CType(Me("o3dRemoveSpec"),Boolean)
            End Get
            Set
                Me("o3dRemoveSpec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property XUpAxis() As Byte
            Get
                Return CType(Me("XUpAxis"),Byte)
            End Get
            Set
                Me("XUpAxis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property X3dUpAxis() As Byte
            Get
                Return CType(Me("X3dUpAxis"),Byte)
            End Get
            Set
                Me("X3dUpAxis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property XScale() As String
            Get
                Return CType(Me("XScale"),String)
            End Get
            Set
                Me("XScale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property X3dScale() As String
            Get
                Return CType(Me("X3dScale"),String)
            End Get
            Set
                Me("X3dScale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowAlpha() As Boolean
            Get
                Return CType(Me("ShowAlpha"),Boolean)
            End Get
            Set
                Me("ShowAlpha") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property nickname() As String
            Get
                Return CType(Me("nickname"),String)
            End Get
            Set
                Me("nickname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property fpsLimit() As Integer
            Get
                Return CType(Me("fpsLimit"),Integer)
            End Get
            Set
                Me("fpsLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 128, 0")>  _
        Public Property SelectionColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SelectionColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SelectionColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TexAutoReload() As Boolean
            Get
                Return CType(Me("TexAutoReload"),Boolean)
            End Get
            Set
                Me("TexAutoReload") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowAllParts() As Boolean
            Get
                Return CType(Me("ShowAllParts"),Boolean)
            End Get
            Set
                Me("ShowAllParts") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.O3D_Test.My.MySettings
            Get
                Return Global.O3D_Test.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
